import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  ArrowDownRight, ArrowRight, ArrowUpRight, BadgeIndianRupee, Bell, CalendarClock,
  ChevronRight, CircleAlert, ClipboardList, Clock3, Gavel,
  Home, Images, IndianRupee, Layers3, LoaderCircle, MapPin, Menu,
  Mountain, Navigation, PackageCheck, Pencil, Phone, RefreshCw, ReceiptText,
  ShieldCheck, Truck, UserRound, X
} from "lucide-react";

/*
  StoneRate Transporter Homepage
  - One-file React frontend with embedded CSS
  - Dependencies: react, lucide-react
  - Mock data is isolated in MOCK_DATA. Live props always take precedence.
*/

// Illustrated image icons for the quick-summary stat cards
const STAT_ICONS = {
  availableTrips: "https://cdn.jsdelivr.net/gh/shyam7291/Image-icons@main/availabletrips.png",
  tripsToday: "https://cdn.jsdelivr.net/gh/shyam7291/Image-icons@main/triptoday.png",
  inTransit: "https://cdn.jsdelivr.net/gh/shyam7291/Image-icons@main/intransit.png",
  completed: "https://cdn.jsdelivr.net/gh/shyam7291/Image-icons@main/completed.png"
};

const MOCK_DATA = {
  transporter: {
    publicId: "TR-1048", name: "Ramesh", companyName: "Ramesh Logistics", phone: "+91 98765 43210",
    profilePhotoUrl: "", verified: true, city: "Bengaluru", state: "Karnataka", available: true
  },
  summary: { availableTrips: 8, tripsToday: 3, inTransit: 1, completedTrips: 12 },
  marketRates: [
    { id: "mr-20", materialName: "Crushed Stone", category: "20mm", startingRate: 1200, unit: "ton", updatedAt: "Today, 8:45 AM", movementType: "up", movementAmount: 150, historyPoints: [16, 18, 17, 22, 20, 25, 24, 29], tone: "emerald" },
    { id: "mr-40", materialName: "Crushed Stone", category: "40mm", startingRate: 980, unit: "ton", updatedAt: "Today, 8:40 AM", movementType: "stable", movementAmount: 0, historyPoints: [20, 21, 19.8, 20.6, 19.9, 21, 20.4, 20.7], tone: "orange" },
    { id: "mr-black", materialName: "Black Stone", category: "Premium", startingRate: 1450, unit: "ton", updatedAt: "Today, 8:35 AM", movementType: "down", movementAmount: 80, historyPoints: [28, 26, 27, 23, 25, 21, 22, 19], tone: "violet" }
  ],
  routes: [
    { id: "r1", pickup: "Hosur", drop: "Bengaluru", distanceKm: 48, demand: "High", vehicle: "16 Tyre" },
    { id: "r2", pickup: "Kolar", drop: "Whitefield", distanceKm: 64, demand: "Medium", vehicle: "14 Tyre" },
    { id: "r3", pickup: "Hoskote", drop: "KR Puram", distanceKm: 26, demand: "High", vehicle: "10 Tyre" },
    { id: "r4", pickup: "Devanahalli", drop: "Yelahanka", distanceKm: 24, demand: "Low", vehicle: "6 Tyre" }
  ],
  recentOrders: [
    { id: "o1", deliveryId: "ST-DEL-24819", source: "StoneRate", status: "New", pickupName: "Shree Balaji Crusher, Hoskote", pickupAddress: "Hoskote Industrial Area", pickupPhone: "+91 98765 01010", dropName: "Ganesh Traders, Whitefield", dropAddress: "Hope Farm, Whitefield", dropPhone: "+91 98765 02020", distanceKm: 32, materialName: "20mm Crushed Stone", materialType: "Stone", quantity: 16, quantityUnit: "tons", vehicleCount: 1, pickupTime: "Today · 10:30 AM", arrivalWindow: "11:45 AM–12:15 PM", tripEarning: 3200 },
    { id: "o2", deliveryId: "ST-DEL-24802", source: "StoneRate", status: "In Transit", pickupName: "Sri Lakshmi Stone Works, Kolar", pickupAddress: "NH 75, Kolar", pickupPhone: "+91 98765 03030", dropName: "Metro Buildmart, Indiranagar", dropAddress: "100 Feet Road", dropPhone: "+91 98765 04040", distanceKm: 57, materialName: "40mm Crushed Stone", materialType: "Stone", quantity: 18, quantityUnit: "tons", vehicleCount: 1, pickupTime: "Today · 7:00 AM", arrivalWindow: "10:30–11:00 AM", tripEarning: 4100 },
    { id: "o3", deliveryId: "MAN-00941", source: "Manual", status: "Accepted", pickupName: "Kaveri Sand Yard, Hoskote", pickupAddress: "Old Madras Road", pickupPhone: "+91 98765 05050", dropName: "Ananya Constructions, KR Puram", dropAddress: "Seegehalli Main Road", dropPhone: "+91 98765 06060", distanceKm: 29, materialName: "Morang", materialType: "Sand", quantity: 50, quantityUnit: "buckets", vehicleCount: 1, pickupTime: "Tomorrow · 8:15 AM", arrivalWindow: "9:30–10:00 AM", tripEarning: 2850 }
  ],
  nextPickup: { pickupPlant: "Shree Balaji Crusher", material: "20mm", quantity: "16 tons", scheduledTime: "10:30 AM", distanceKm: 12, phone: "+91 98765 01010", orderId: "o1" },
  orderSnapshot: { totalTrucks: 18, totalQuantity: 286, quantityUnit: "tons", totalOrders: 24, thisWeek: 7, thisMonth: 19, weekBars: [38, 62, 46, 80, 68, 92, 56] },
  notifications: [
    { id: "n1", title: "New trip near Hoskote", message: "A 16-ton stone delivery is available.", type: "trip", createdAt: "4 min ago", read: false },
    { id: "n2", title: "Payment processed", message: "₹3,200 has been sent to your wallet.", type: "payment", createdAt: "2 hr ago", read: false },
    { id: "n3", title: "Pickup reminder", message: "Your pickup begins at 10:30 AM.", type: "reminder", createdAt: "Yesterday", read: true }
  ]
};

const money = (value = 0) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value) || 0);
const cx = (...items) => items.filter(Boolean).join(" ");

// Shared transporter navigation (identical across Samples / Bidding / Home / Orders / Profile)
const NAV_ITEMS = [
  { label: "Samples", icon: Images },
  { label: "Bidding", icon: Gavel },
  { label: "Home", icon: Home },
  { label: "Orders", icon: PackageCheck },
  { label: "Profile", icon: UserRound }
];
const NAV_ICON_SIZE = 19;
const NAV_ICON_ACTIVE = 20;

const styles = `
:root{--ink:#10243e;--muted:#65758b;--line:#dfe8ee;--indigo:#2457e6;--violet:#6c4ee7;--cyan:#00a9c7;--green:#19a875;--orange:#f28a33;--blue:#318dde;--red:#e95c69;--surface:rgba(255,255,255,.88);font-family:"Plus Jakarta Sans",Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:#edf5f6}
/* ==== Shared StoneRate transporter navigation (reference: Bidding page) ==== */
.bd-shell{width:min(100% - 28px,1120px);max-width:100%;margin:auto}
.bd-header{position:sticky;top:0;z-index:40;border-bottom:1px solid rgba(218,222,239,.72);background:rgba(255,255,255,.82);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.bd-header-inner{min-height:64px;padding:8px 0;display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;align-items:center;gap:10px}
.bd-icon-btn{width:38px;height:38px;flex:0 0 auto;border:1px solid #e4e7f1;border-radius:12px;background:rgba(255,255,255,.9);color:#10243e;display:grid;place-items:center;position:relative;padding:0;transition:border-color .2s,transform .2s}
.bd-icon-btn:hover{border-color:#cbd1ee;transform:translateY(-1px)}
.bd-icon-btn>svg{width:19px;height:19px}
.bd-greeting{min-width:0;display:flex;flex-direction:column;justify-content:center;gap:2px}
.bd-greeting strong,.bd-greeting small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.bd-greeting strong{font-size:clamp(14px,4.2vw,17px);line-height:1.15;letter-spacing:-.3px;color:#10243e}
.bd-greeting small{font-size:clamp(10.5px,3vw,12px);line-height:1.2;color:#65758b;font-weight:600}
.bd-logo{display:flex;align-items:center;gap:6px;font-size:clamp(17px,5vw,21px);line-height:1;font-weight:900;letter-spacing:-.6px;white-space:nowrap;color:#10243e}
.bd-logo-mark{width:30px;height:30px;flex:0 0 auto;border-radius:9px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,#2457e6,#6c4ee7 55%,#00a9c7);box-shadow:0 6px 16px rgba(91,108,255,.22)}
.bd-logo-mark>svg{width:17px;height:17px}
.bd-logo-rate{color:#6c4ee7}
.bd-notify-dot{position:absolute;right:7px;top:6px;width:8px;height:8px;border-radius:50%;background:#f05b68;border:2px solid #fff}
.bd-desktop-nav{display:none}
.bd-bottom{position:fixed;z-index:35;left:12px;right:12px;bottom:max(10px,env(safe-area-inset-bottom));height:72px;border:1px solid rgba(217,221,237,.9);border-radius:23px;background:rgba(255,255,255,.9);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 16px 38px rgba(32,42,91,.18);display:grid;grid-template-columns:repeat(5,1fr);padding:7px 7px 5px}
.bd-nav-item{border:0;background:transparent;color:#7a829b;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;padding:0;min-width:0;font-size:8.5px;line-height:normal;font-weight:800;position:relative;border-radius:14px;cursor:pointer}
.bd-nav-item:hover{background:#f4f5fb;color:#5260c7}
.bd-nav-item.active{color:#4f5dd4}
.bd-nav-item>svg{width:19px;height:19px;stroke-width:2;flex:0 0 auto}
.bd-nav-item>span:last-child{font-size:8.5px;line-height:normal;font-weight:800}
.bd-active-icon{width:45px;height:45px;flex:0 0 auto;margin-top:-24px;border:5px solid #eff1fa;border-radius:17px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,#2457e6,#6c4ee7 58%,#00a9c7);box-shadow:0 9px 21px rgba(86,94,213,.31)}
.bd-active-icon>svg{width:20px;height:20px;stroke-width:2}
.bd-nav-badge{position:absolute;top:5px;right:18%;background:#f05b68;color:#fff;border:2px solid #fff;border-radius:99px;min-width:15px;height:15px;padding:0 2px;line-height:11px;font-size:7px;font-weight:800}
@media(max-width:390px){.bd-header-inner{gap:7px}.bd-icon-btn{width:36px;height:36px}.bd-logo{gap:5px}.bd-logo-mark{width:28px;height:28px}}
@media(max-width:359px){.bd-greeting small{display:none}}
@media(min-width:700px){.bd-shell{width:min(100% - 42px,1120px)}.bd-greeting strong{font-size:18px}.bd-greeting small{font-size:12.5px}.bd-logo{font-size:22px}}
@media(min-width:980px){.bd-header-inner{min-height:72px;grid-template-columns:auto auto 1fr auto auto}.bd-desktop-nav{display:flex;align-items:center;justify-content:center;gap:4px}.bd-desktop-nav button{border:0;background:transparent;padding:9px 12px;color:#69718c;font-size:12px;font-weight:800;border-radius:10px;cursor:pointer}.bd-desktop-nav button.active,.bd-desktop-nav button:hover{color:#4f5ed4;background:#eef0ff}.bd-logo{position:absolute;left:50%;transform:translateX(-50%)}.bd-bottom{display:none}}
/* ==== end shared navigation ==== */
*{box-sizing:border-box}html{scroll-behavior:smooth;overflow-x:hidden}body{margin:0;background:linear-gradient(180deg,#f6fbfa,#edf5f6 46%,#f4f1fb);min-width:320px;max-width:100%;overflow-x:hidden}button,a{font:inherit}button{cursor:pointer}button:focus-visible,a:focus-visible,[tabindex]:focus-visible{outline:3px solid rgba(91,108,255,.32);outline-offset:2px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.sr-app{min-height:100vh;position:relative;isolation:isolate;padding-bottom:104px;max-width:100%;overflow-x:hidden}.sr-app:before,.sr-app:after{content:"";position:fixed;z-index:-1;border-radius:999px;filter:blur(8px);pointer-events:none}.sr-app:before{width:300px;height:300px;left:-140px;top:100px;background:radial-gradient(circle,rgba(99,111,255,.16),transparent 68%)}.sr-app:after{width:360px;height:360px;right:-190px;top:460px;background:radial-gradient(circle,rgba(34,189,233,.14),transparent 68%)}
.sr-shell{width:min(100% - 28px,1180px);margin:auto;max-width:100%}.sr-icon-btn{border:1px solid #e4e7f1;background:rgba(255,255,255,.84);color:var(--ink);width:36px;height:36px;border-radius:12px;display:grid;place-items:center;position:relative;transition:.2s ease}.sr-icon-btn:hover{transform:translateY(-1px);border-color:#cbd1ee}
.sr-main{padding-top:16px}.sr-hero{position:relative;overflow:hidden;border-radius:24px;padding:20px;color:white;background:linear-gradient(135deg,#102a43,#174c78 52%,#087f8c);box-shadow:0 18px 40px rgba(82,92,194,.2)}.sr-hero:before{content:"";position:absolute;width:190px;height:190px;border-radius:50%;right:-70px;top:-100px;background:rgba(255,255,255,.14)}.sr-hero:after{content:"";position:absolute;width:130px;height:130px;border-radius:38px;right:28%;bottom:-100px;transform:rotate(25deg);background:rgba(255,255,255,.08)}.sr-hero-content{position:relative;z-index:1}.sr-eyebrow{font-size:10px;letter-spacing:1.6px;font-weight:850;color:#5962a0}.sr-hero .sr-eyebrow{color:rgba(255,255,255,.78)}.sr-hero h1{font-size:27px;line-height:1.02;margin:8px 0 8px;letter-spacing:-1px}.sr-hero-copy{font-size:13px;line-height:1.55;color:rgba(255,255,255,.86);max-width:560px;margin:0}.sr-hero-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.sr-hero-chip{display:flex;align-items:center;gap:6px;border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.13);padding:8px 10px;border-radius:12px;font-size:11px;font-weight:700;backdrop-filter:blur(8px)}.sr-online-dot{width:8px;height:8px;background:#5ef2ad;border:2px solid rgba(255,255,255,.45);border-radius:50%;box-shadow:0 0 0 3px rgba(94,242,173,.14)}.sr-availability{margin-top:15px;display:flex;align-items:center;justify-content:space-between;gap:16px;background:rgba(18,25,54,.17);border:1px solid rgba(255,255,255,.16);border-radius:16px;padding:11px 12px}.sr-availability b{font-size:12px;display:block}.sr-availability span{font-size:10px;color:rgba(255,255,255,.78)}.sr-switch{width:49px;height:28px;padding:3px;border:0;border-radius:99px;background:rgba(11,19,48,.32);transition:.2s}.sr-switch.on{background:#16b67c}.sr-switch-knob{display:block;width:22px;height:22px;background:white;border-radius:50%;box-shadow:0 3px 8px rgba(0,0,0,.15);transition:.2s}.sr-switch.on .sr-switch-knob{transform:translateX(21px)}
.sr-section{margin-top:25px}.sr-section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:12px}.sr-section-head h2{font-size:19px;letter-spacing:-.55px;margin:4px 0 0}.sr-section-head p{color:var(--muted);font-size:12px;margin:5px 0 0;line-height:1.45}.sr-pill-btn{border:1px solid #dfe3f1;background:rgba(255,255,255,.8);color:#4f5876;border-radius:99px;padding:8px 11px;font-size:11px;font-weight:800;display:inline-flex;align-items:center;gap:4px;white-space:nowrap;transition:.2s}.sr-pill-btn:hover{border-color:#aeb8ef;color:#4858d5;transform:translateY(-1px)}
.sr-scroller{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(265px,84%);gap:11px;overflow-x:auto;scroll-snap-type:x mandatory;padding:2px 1px 8px;scrollbar-width:none}.sr-scroller::-webkit-scrollbar{display:none}.sr-scroller>*{scroll-snap-align:start}.sr-card{background:var(--surface);border:1px solid rgba(222,225,239,.92);border-radius:20px;box-shadow:0 9px 28px rgba(48,58,108,.07)}.sr-benefit{padding:15px;min-height:168px;display:flex;flex-direction:column}.sr-benefit.emerald{background:linear-gradient(145deg,#fff,#effbf7)}.sr-benefit.violet{background:linear-gradient(145deg,#fff,#f4f0ff)}.sr-benefit.orange{background:linear-gradient(145deg,#fff,#fff5ec)}.sr-benefit-icon{width:40px;height:40px;border-radius:13px;display:grid;place-items:center;color:white;margin-bottom:12px}.emerald .sr-benefit-icon{background:linear-gradient(135deg,#18b27d,#5ed4a9)}.violet .sr-benefit-icon{background:linear-gradient(135deg,#5b6cff,#9257f3)}.orange .sr-benefit-icon{background:linear-gradient(135deg,#f68a32,#ffb44f)}.sr-benefit h3{font-size:15px;margin:0 0 5px}.sr-benefit p{font-size:11.5px;line-height:1.52;color:var(--muted);margin:0 0 11px}.sr-mini-tag{align-self:flex-start;margin-top:auto;padding:6px 8px;border-radius:8px;font-size:9.5px;font-weight:850}.emerald .sr-mini-tag{color:#087f58;background:#dff8ed}.violet .sr-mini-tag{color:#6840d6;background:#eae2ff}.orange .sr-mini-tag{color:#bd5e13;background:#ffead6}
.sr-summary-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.sr-stat{padding:12px 14px 14px;position:relative;overflow:hidden;display:flex;flex-direction:column}.sr-stat-top{display:flex;align-items:center;justify-content:space-between}.sr-stat-icon{width:clamp(96px,58%,150px);aspect-ratio:10/7;display:block;overflow:hidden;background:transparent;border-radius:0}.sr-stat-img{width:100%;height:100%;object-fit:cover;object-position:50% 42%;display:block;user-select:none;-webkit-user-drag:none;filter:drop-shadow(0 6px 10px rgba(48,58,108,.12))}.sr-stat-value{display:block;font-size:26px;font-weight:850;letter-spacing:-.7px;margin-top:6px;line-height:1}.sr-stat-label{display:block;color:var(--muted);font-size:12px;margin-top:3px}.sr-stat.indigo .sr-stat-icon,.sr-stat.green .sr-stat-icon,.sr-stat.orange .sr-stat-icon,.sr-stat.cyan .sr-stat-icon{background:transparent}
.sr-rate{border-top:4px solid var(--tone);padding:14px;background:var(--tint);min-height:224px}.sr-rate-top{display:flex;align-items:center;justify-content:space-between}.sr-material-mark{width:39px;height:39px;border-radius:13px;display:grid;place-items:center;background:white;color:var(--tone);box-shadow:0 5px 15px rgba(59,67,106,.08)}.sr-updated{font-size:9.5px;color:var(--muted)}.sr-rate-name{margin-top:13px}.sr-rate-name strong{display:block;font-size:18px}.sr-rate-name span{font-size:11px;color:var(--muted)}.sr-price-row{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-top:13px}.sr-starting{font-size:9px;letter-spacing:1px;color:var(--muted);font-weight:850}.sr-price{font-size:23px;font-weight:900;letter-spacing:-.8px;margin-top:2px}.sr-price small{font-size:10px;color:var(--muted);font-weight:700}.sr-movement{display:flex;align-items:center;gap:3px;border-radius:99px;background:color-mix(in srgb,var(--tone) 13%,white);color:var(--tone);padding:6px 8px;font-size:9px;font-weight:850;white-space:nowrap}.sr-spark{margin-top:8px;width:100%;height:48px;display:block}
.sr-route-card{padding:14px;min-height:132px}.sr-route-title{display:flex;align-items:center;gap:7px;font-size:13px;font-weight:850}.sr-route-meta{font-size:10.5px;color:var(--muted);margin:9px 0 12px}.sr-route-foot{display:flex;align-items:center;justify-content:space-between;gap:8px}.sr-demand{border-radius:99px;padding:6px 8px;font-size:9px;font-weight:850}.sr-demand.high{color:#bc5a10;background:#fff0df}.sr-demand.medium{color:#6540d3;background:#eee8ff}.sr-demand.low{color:#2773b4;background:#e7f3fd}.sr-vehicle{font-size:10px;color:#59617b;font-weight:750}
.sr-pickup{padding:16px;overflow:hidden;position:relative;background:linear-gradient(135deg,#161d44,#3f367e 62%,#1f7995);color:white;border:0}.sr-pickup:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-70px;top:-75px;background:rgba(255,255,255,.08)}.sr-pickup-grid{display:grid;gap:13px;position:relative;z-index:1}.sr-pickup-title{display:flex;align-items:center;gap:8px}.sr-pickup-title span{font-size:10px;color:#aab4ed;font-weight:800;letter-spacing:1px}.sr-pickup h3{font-size:18px;margin:5px 0}.sr-pickup-detail{display:flex;flex-wrap:wrap;gap:7px;color:#dce0f9;font-size:10.5px}.sr-pickup-detail span{display:flex;align-items:center;gap:4px}.sr-actions{display:flex;gap:8px}.sr-btn{border:0;border-radius:12px;padding:10px 13px;font-weight:850;font-size:11px;display:inline-flex;align-items:center;justify-content:center;gap:6px;transition:.2s ease}.sr-btn:hover{transform:translateY(-1px)}.sr-btn-primary{color:white;background:linear-gradient(135deg,#2457e6,#6c4ee7);box-shadow:0 8px 18px rgba(91,108,255,.22)}.sr-btn-light{background:white;color:#30385f}.sr-btn-ghost{background:rgba(255,255,255,.13);color:white;border:1px solid rgba(255,255,255,.18)}
.sr-orders{display:grid;gap:11px}.sr-order{padding:14px}.sr-order-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.sr-order-id{font-size:12px;font-weight:900}.sr-source{display:inline-flex;align-items:center;gap:4px;margin-top:5px;border-radius:7px;padding:5px 7px;font-size:8.7px;font-weight:850}.sr-source.stonerate{background:#ebe9ff;color:#6545d8}.sr-source.manual{background:#f5f1eb;color:#9a6836}.sr-status{border-radius:99px;padding:6px 8px;font-size:9px;font-weight:850;white-space:nowrap}.status-new{background:#e8edff;color:#4d60d8}.status-accepted,.status-at-pickup,.status-loading{background:#fff0df;color:#bd631b}.status-in-transit{background:#e1f5fc;color:#197b9c}.status-delivered{background:#def7ec;color:#13815f}.status-cancelled{background:#fde7ea;color:#bc4551}.sr-timeline{margin:14px 0;position:relative}.sr-stop{display:grid;grid-template-columns:15px 1fr auto;gap:8px;align-items:start;position:relative}.sr-stop+.sr-stop{margin-top:13px}.sr-stop:first-child:after{content:"";position:absolute;width:1px;height:19px;left:6px;top:14px;background:#cfd4e7}.sr-timeline.manual-only .sr-stop:first-child:after{display:none}.sr-stop-dot{width:13px;height:13px;border:3px solid white;border-radius:50%;box-shadow:0 0 0 1px #d5daea}.sr-stop-dot.pickup{background:#23af7e}.sr-stop-dot.drop{background:#7860ed}.sr-stop small{display:block;color:var(--muted);font-size:8.5px;text-transform:uppercase;letter-spacing:.8px}.sr-stop strong{display:block;font-size:10.5px;margin-top:2px;line-height:1.35}.sr-distance{font-size:9.5px;color:#59617b;background:#f1f3f9;padding:5px 7px;border-radius:8px}.sr-order-info{display:grid;grid-template-columns:1fr auto;gap:12px;border-top:1px solid #eceef5;border-bottom:1px solid #eceef5;padding:11px 0}.sr-order-info small{display:block;color:var(--muted);font-size:8.5px}.sr-order-info strong{font-size:11px;line-height:1.35}.sr-earning{text-align:right}.sr-earning strong{font-size:16px;color:#15916a}.sr-order-time{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px;color:#59617b;font-size:9.5px}.sr-order-time span{display:flex;align-items:center;gap:5px}.sr-order-action{width:100%;margin-top:11px}
.sr-earnings{padding:16px}.sr-earn-top{display:flex;align-items:center;justify-content:space-between}.sr-earn-top h3{margin:0;font-size:17px}.sr-earn-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:13px}.sr-earn-metric{background:#f7f8fc;border-radius:13px;padding:10px}.sr-earn-metric small{display:block;color:var(--muted);font-size:9px}.sr-earn-metric strong{display:block;font-size:15px;margin-top:3px}.sr-bars{height:56px;display:flex;align-items:end;gap:6px;margin:14px 0 12px;padding:0 4px;border-bottom:1px solid #e6e8f1}.sr-bar{flex:1;min-width:9px;border-radius:5px 5px 0 0;background:linear-gradient(180deg,#7c65f0,#5b6cff);opacity:.72;transition:.2s}.sr-bar:hover{opacity:1}.sr-earn-foot{display:flex;align-items:center;justify-content:space-between;gap:12px}.sr-progress-copy{font-size:9.5px;color:var(--muted)}
.sr-empty,.sr-error{padding:25px;text-align:center}.sr-empty-icon,.sr-error-icon{width:46px;height:46px;border-radius:15px;display:grid;place-items:center;margin:0 auto 10px;background:#eceeff;color:#5b6cff}.sr-error-icon{background:#fdebed;color:#d74d5a}.sr-empty h3,.sr-error h3{font-size:14px;margin:0}.sr-empty p,.sr-error p{color:var(--muted);font-size:10.5px;line-height:1.5;margin:5px auto 12px;max-width:330px}.sr-skeleton{position:relative;overflow:hidden;background:#e9ebf3;border-radius:11px}.sr-skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.72),transparent);animation:shimmer 1.3s infinite}@keyframes shimmer{to{transform:translateX(100%)}}.sr-skeleton-card{height:205px;border-radius:20px}.sr-skeleton-stat{height:132px;border-radius:20px}
.sr-refresh{position:fixed;right:16px;bottom:100px;z-index:25;width:42px;height:42px;border:0;border-radius:15px;color:white;background:linear-gradient(135deg,#2457e6,#6c4ee7);box-shadow:0 10px 22px rgba(75,83,178,.28);display:grid;place-items:center}.sr-refresh.spinning svg{animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.sr-overlay{position:fixed;inset:0;background:rgba(15,20,48,.42);z-index:70;backdrop-filter:blur(3px);animation:fade .18s ease}@keyframes fade{from{opacity:0}}.sr-drawer{position:fixed;z-index:71;right:0;top:0;bottom:0;width:min(90vw,390px);background:#f8f9fd;padding:18px;box-shadow:-20px 0 48px rgba(25,30,68,.2);animation:slide .25s ease;overflow:auto}@keyframes slide{from{transform:translateX(100%)}}.sr-drawer-head,.sr-modal-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.sr-drawer-head h2,.sr-modal-head h2{font-size:18px;margin:0}.sr-notification{padding:13px;margin-top:10px;display:grid;grid-template-columns:34px 1fr;gap:10px;position:relative}.sr-notification.unread{border-color:#bfc6f3;background:#fff}.sr-notification-icon{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;background:#eceeff;color:#5b6cff}.sr-notification h3{font-size:11px;margin:1px 0 4px}.sr-notification p,.sr-notification time{font-size:9.5px;color:var(--muted);margin:0;line-height:1.45}.sr-unread-mark{position:absolute;width:7px;height:7px;background:#5b6cff;border-radius:50%;right:11px;top:12px}.sr-modal-wrap{position:fixed;inset:0;z-index:72;display:grid;place-items:center;padding:16px}.sr-modal{width:min(100%,520px);max-height:88vh;overflow:auto;background:white;border-radius:23px;padding:18px;box-shadow:0 24px 60px rgba(17,23,61,.28);animation:pop .2s ease}@keyframes pop{from{opacity:0;transform:scale(.97) translateY(8px)}}.sr-modal-body{margin-top:15px}.sr-modal-route{background:#f6f7fc;border-radius:16px;padding:13px}.sr-modal-row{display:flex;justify-content:space-between;gap:16px;padding:10px 0;border-bottom:1px solid #eceef5;font-size:11px}.sr-modal-row:last-child{border:0}.sr-modal-row span{color:var(--muted)}.sr-toast{position:fixed;left:50%;bottom:102px;transform:translateX(-50%);z-index:90;background:#171d3d;color:white;padding:10px 14px;border-radius:12px;box-shadow:0 10px 24px rgba(20,26,61,.25);font-size:11px;font-weight:750;animation:pop .2s ease;white-space:nowrap}

.sr-story-rail{display:grid;grid-auto-flow:column;grid-auto-columns:88%;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:2px 1px 9px}.sr-story-rail::-webkit-scrollbar{display:none}.sr-story{scroll-snap-align:center;min-height:188px;padding:19px;position:relative;overflow:hidden;color:white;border:0;background:linear-gradient(135deg,#102a43,#174c78 56%,#087f8c)}.sr-story:nth-child(2){background:linear-gradient(135deg,#075e54,#0f8f79 58%,#40c9a2)}.sr-story:nth-child(3){background:linear-gradient(135deg,#38246b,#6646b4 55%,#9874dc)}.sr-story:nth-child(4){background:linear-gradient(135deg,#76351d,#c45d2d 56%,#ff9d5c)}.sr-story:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-52px;top:-62px;background:rgba(255,255,255,.12)}.sr-story-icon{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.2);backdrop-filter:blur(8px)}.sr-story .sr-eyebrow{margin-top:18px;color:rgba(255,255,255,.72)}.sr-story h2{font-size:21px;margin:5px 0 7px;letter-spacing:-.6px}.sr-story p{font-size:11.5px;line-height:1.5;color:rgba(255,255,255,.82);max-width:420px;margin:0}.sr-story-dots{display:flex;justify-content:center;gap:6px;margin-top:5px}.sr-story-dot{width:6px;height:6px;border-radius:99px;background:#cbd8de}.sr-story-dot.active{width:22px;background:#2457e6}.sr-order-snapshot{padding:17px;background:linear-gradient(145deg,#fff,#f1f8f7)}.sr-snapshot-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:14px}.sr-snapshot-metric{padding:12px;border-radius:15px;background:rgba(255,255,255,.88);border:1px solid #e0eaeb}.sr-snapshot-metric small{display:block;color:var(--muted);font-size:9px}.sr-snapshot-metric strong{display:block;font-size:17px;margin-top:4px}.sr-snapshot-metric span{font-size:9px;color:#087f8c;font-weight:800}.sr-order .sr-earning{display:none}.sr-order-info{grid-template-columns:1fr}.sr-order-info>div:first-child{display:grid;grid-template-columns:1fr auto;gap:8px}.sr-order-info>div:first-child:after{content:"Verified load";align-self:center;color:#087f8c;background:#e1f7f2;padding:6px 8px;border-radius:99px;font-size:8.5px;font-weight:850}
@media(min-width:700px){.sr-shell{width:min(100% - 42px,1180px)}.sr-main{padding-top:22px}.sr-hero{padding:25px}.sr-hero h1{font-size:34px}.sr-hero-layout{display:grid;grid-template-columns:1fr 280px;align-items:end;gap:25px}.sr-availability{margin:0}.sr-scroller{grid-auto-columns:minmax(280px,45%)}.sr-summary-grid{grid-template-columns:repeat(4,1fr);gap:14px}.sr-stat{padding:14px 16px 16px}.sr-stat-icon{width:clamp(100px,56%,150px)}.sr-stat-value{font-size:28px}.sr-orders{grid-template-columns:repeat(2,1fr)}.sr-pickup-grid{grid-template-columns:1fr auto;align-items:center}.sr-earnings{display:grid;grid-template-columns:1fr 1.12fr;gap:24px}.sr-bars{margin-top:0}.sr-earn-foot{grid-column:2}}
@media(min-width:980px){.sr-app{padding-bottom:38px}.sr-refresh{bottom:24px;right:28px}.sr-toast{bottom:28px}.sr-scroller{overflow:visible;grid-auto-flow:initial;grid-auto-columns:initial}.sr-benefits-grid{grid-template-columns:repeat(3,1fr)}.sr-rates-grid{grid-template-columns:repeat(3,1fr)}.sr-routes-grid{grid-template-columns:repeat(4,1fr)}.sr-orders{grid-template-columns:repeat(3,1fr)}.sr-section{margin-top:30px}.sr-hero{padding:28px 30px}.sr-story-rail{grid-template-columns:repeat(4,1fr);grid-auto-flow:initial;grid-auto-columns:initial;overflow:visible}.sr-story{min-height:205px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
`;

function IconButton({ label, children, className = "", ...props }) {
  return <button className={cx("sr-icon-btn", className)} aria-label={label} {...props}>{children}</button>;
}

function SectionHead({ eyebrow, title, subtitle, action, onAction }) {
  return <div className="sr-section-head"><div>{eyebrow && <div className="sr-eyebrow">{eyebrow}</div>}<h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action && <button className="sr-pill-btn" onClick={onAction}>{action}<ChevronRight size={13}/></button>}</div>;
}

function EmptyState({ icon: Icon = PackageCheck, title, text, action, onAction }) {
  return <div className="sr-card sr-empty"><div className="sr-empty-icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p>{action && <button className="sr-btn sr-btn-primary" onClick={onAction}>{action}</button>}</div>;
}

function ErrorPanel({ onRetry }) {
  return <div className="sr-card sr-error" role="alert"><div className="sr-error-icon"><CircleAlert size={22}/></div><h3>We could not load your dashboard</h3><p>No demo data has been substituted. Check your connection and retry the live API request.</p><button className="sr-btn sr-btn-primary" onClick={onRetry}><RefreshCw size={14}/>Retry</button></div>;
}

function Skeletons({ type, count = 3 }) {
  return <div className={type === "stat" ? "sr-summary-grid" : "sr-scroller"}>{Array.from({ length: count }).map((_,i)=><div key={i} className={cx("sr-skeleton", type === "stat" ? "sr-skeleton-stat" : "sr-skeleton-card")} aria-hidden="true"/>)}</div>;
}

function Sparkline({ points = [], color = "#19a875", id }) {
  const data = points.length > 1 ? points : [20,21,19.8,20.7,20.1,21.1,20.5,20.8];
  const w=240,h=50,pad=3,min=Math.min(...data),max=Math.max(...data),range=max-min||1;
  const coords=data.map((n,i)=>[pad+(i*(w-2*pad))/(data.length-1),pad+((max-n)*(h-2*pad))/range]);
  const d=coords.map(([x,y],i)=>(i?"L":"M")+x.toFixed(1)+" "+y.toFixed(1)).join(" ");
  const fill=`${d} L ${coords.at(-1)[0].toFixed(1)} ${h} L ${coords[0][0].toFixed(1)} ${h} Z`;
  const gid=`spark-${String(id).replace(/[^a-z0-9]/gi,"")}`;
  return <svg className="sr-spark" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" role="img" aria-label="Recent market movement"><defs><linearGradient id={gid} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><path d={fill} fill={`url(#${gid})`}/><path d={d} fill="none" stroke={color} strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/><circle cx={coords.at(-1)[0]} cy={coords.at(-1)[1]} r="3" fill={color} stroke="white" strokeWidth="1.5"/></svg>;
}

function MarketRateCard({ rate }) {
  const palette={emerald:["#19a875","#effbf7"],orange:["#f28a33","#fff6ed"],violet:["#6f64e8","#f4f2ff"],blue:["#318dde","#eef7ff"]};
  const [tone,tint]=palette[rate.tone]||palette.violet;
  const Move=rate.movementType==="up"?ArrowUpRight:rate.movementType==="down"?ArrowDownRight:ArrowRight;
  const movement=rate.movementType==="stable"?"Stable / 24h":`${rate.movementType==="up"?"↑":"↓"} ${money(rate.movementAmount)} / 24h`;
  return <article className="sr-card sr-rate" style={{"--tone":tone,"--tint":tint}}><div className="sr-rate-top"><div className="sr-material-mark"><Mountain size={21}/></div><time className="sr-updated">{rate.updatedAt}</time></div><div className="sr-rate-name"><strong>{rate.category}</strong><span>{rate.materialName}</span></div><div className="sr-price-row"><div><div className="sr-starting">STARTING AT</div><div className="sr-price">{money(rate.startingRate)} <small>/{rate.unit}</small></div></div><span className="sr-movement"><Move size={12}/>{movement}</span></div><Sparkline points={rate.historyPoints} color={tone} id={rate.id}/></article>;
}

function OrderCard({ order, onOpen, onAccept, onNavigate }) {
  const action = order.status === "New" ? "Accept Trip" : order.status === "In Transit" ? "Open Navigation" : order.status === "Accepted" ? "View Details" : "Update Status";
  const click = action === "Accept Trip" ? () => onAccept(order) : action === "Open Navigation" ? () => onNavigate(order) : () => onOpen(order);
  return <article className="sr-card sr-order"><div className="sr-order-head"><div><div className="sr-order-id">{order.deliveryId}</div><span className={cx("sr-source",order.source.toLowerCase())}>{order.source === "StoneRate" ? <ShieldCheck size={10}/> : <Pencil size={10}/>} {order.source === "StoneRate" ? "By StoneRate" : "Manual"}</span></div><span className={cx("sr-status",`status-${order.status.toLowerCase().replaceAll(" ","-")}`)}>{order.status}</span></div><div className={cx("sr-timeline",order.source === "Manual" && "manual-only")}><div className="sr-stop"><span className="sr-stop-dot pickup"/><div><small>Pickup</small><strong>{order.pickupName}</strong></div><span className="sr-distance">{order.distanceKm} km</span></div>{order.source !== "Manual" && <div className="sr-stop"><span className="sr-stop-dot drop"/><div><small>Drop</small><strong>{order.dropName}</strong></div></div>}</div><div className="sr-order-info"><div><small>MATERIAL</small><strong>{order.materialName}<br/>{order.quantity} {order.quantityUnit} · {order.vehicleCount || 1} truck</strong></div></div><div className="sr-order-time"><span><CalendarClock size={12}/>{order.pickupTime}</span><span><Clock3 size={12}/>{order.arrivalWindow}</span></div><button className="sr-btn sr-btn-primary sr-order-action" onClick={click}>{action}<ArrowRight size={14}/></button></article>;
}

function Modal({ open, title, onClose, children }) {
  const ref=useRef(null);
  useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=e=>{if(e.key==="Escape")onClose();if(e.key==="Tab"&&ref.current){const nodes=[...ref.current.querySelectorAll('button,[href],input,[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",onKey);setTimeout(()=>ref.current?.querySelector("button")?.focus(),0);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",onKey)}},[open,onClose]);
  if(!open)return null;
  return <><div className="sr-overlay" onMouseDown={onClose}/><div className="sr-modal-wrap" role="dialog" aria-modal="true" aria-label={title}><div className="sr-modal" ref={ref} onMouseDown={e=>e.stopPropagation()}><div className="sr-modal-head"><h2>{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={18}/></IconButton></div><div className="sr-modal-body">{children}</div></div></div></>;
}

export default function StoneRateTransporterHomepage({
  transporter, summary, marketRates, recentOrders, routes, nextPickup, orderSnapshot, notifications,
  loading=false, error=null, useMockFallback=true,
  onAvailabilityChange=()=>{}, onRefresh=()=>{}, onRetry=()=>{}, onViewAllRates=()=>{},
  onViewAllOrders=()=>{}, onAcceptTrip=()=>{}, onNavigate=()=>{}, onCall=()=>{},
  onViewEarnings=()=>{}, onBrowseTrips=()=>{}, onNavigation=()=>{}, onNotificationRead=()=>{}, onMenu=()=>{}
}) {
  const pick=(live,key)=>live !== undefined ? live : (useMockFallback ? MOCK_DATA[key] : undefined);
  const t=pick(transporter,"transporter")||{}; const s=pick(summary,"summary");
  const rates=pick(marketRates,"marketRates")||[]; const orders=(pick(recentOrders,"recentOrders")||[]).slice(0,3);
  const routeData=pick(routes,"routes")||[]; const pickup=pick(nextPickup,"nextPickup"); const snapshot=pick(orderSnapshot,"orderSnapshot"); const notes=pick(notifications,"notifications")||[];
  const available=Boolean(t.available); const [drawer,setDrawer]=useState(false); const [selected,setSelected]=useState(null); const [refreshing,setRefreshing]=useState(false); const [toast,setToast]=useState("");
  useEffect(()=>{if(!toast)return;const x=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(x)},[toast]);
  const unread=notes.filter(n=>!n.read).length;
  const closeDrawer=useCallback(()=>setDrawer(false),[]); const closeModal=useCallback(()=>setSelected(null),[]);
  useEffect(()=>{if(!drawer)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=e=>e.key==="Escape"&&closeDrawer();document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key)}},[drawer,closeDrawer]);
  const refresh=async()=>{setRefreshing(true);try{await onRefresh()}finally{setTimeout(()=>setRefreshing(false),500)}};
  const navTo=(label)=>{onNavigation(label);setToast(`${label} selected`)};
  const accept=(order)=>{onAcceptTrip(order);setToast(`Trip ${order.deliveryId} accepted`)};
  const navigate=(payload)=>{onNavigate(payload);setToast("Opening navigation")};
  const call=(phone)=>{onCall(phone); if(typeof window!=="undefined"&&phone) window.location.href=`tel:${phone.replace(/\s/g,"")}`};
  const benefits=[
    {tone:"emerald",icon:ReceiptText,title:"No Hidden Margins",copy:"See the complete trip value and transportation rate. StoneRate keeps pricing clear and transparent.",tag:"Full transparency"},
    {tone:"violet",icon:Layers3,title:"Samples Across Hundreds of Plants",copy:"View material samples and pickup information from Stone Sellers and Sand Yards across multiple locations.",tag:"Verified sources"},
    {tone:"orange",icon:PackageCheck,title:"Pick, Drop & Earn",copy:"Receive direct delivery opportunities from Buyer orders. Accept, pick up, deliver, and earn.",tag:"Direct Buyer orders"}
  ];
  const stats=s?[{label:"Available Trips",value:s.availableTrips,image:STAT_ICONS.availableTrips,tone:"indigo"},{label:"Trips Today",value:s.tripsToday,image:STAT_ICONS.tripsToday,tone:"green"},{label:"In Transit",value:s.inTransit,image:STAT_ICONS.inTransit,tone:"orange"},{label:"Completed",value:s.completedTrips,image:STAT_ICONS.completed,tone:"cyan"}]:[];

  return <div className="sr-app"><style>{styles}</style>
    <header className="bd-header"><div className="bd-shell bd-header-inner">
      <button type="button" className="bd-icon-btn" aria-label="Open menu" onClick={onMenu}><Menu size={19}/></button>
      <div className="bd-greeting"><strong>Hi, {t.name||"Transporter"}</strong><small>Ready for today’s trips?</small></div>
      <div className="bd-logo" aria-label="StoneRate"><span className="bd-logo-mark"><Mountain size={17}/></span><span>Stone<span className="bd-logo-rate">Rate</span></span></div>
      <nav className="bd-desktop-nav" aria-label="Desktop navigation">
        {NAV_ITEMS.map(item => <button type="button" key={item.label} className={item.label === "Home" ? "active" : ""} onClick={() => navTo(item.label)}>{item.label}</button>)}
      </nav>
      <button type="button" className="bd-icon-btn" aria-label={`Notifications, ${unread} unread`} onClick={()=>setDrawer(true)}><Bell size={19}/>{unread > 0 && <span className="bd-notify-dot"/>}</button>
    </div></header>
    <main className="sr-shell sr-main">
      {error ? <ErrorPanel onRetry={onRetry}/> : <>
      <section aria-label="StoneRate transporter highlights">
        <div className="sr-story-rail">
          <article className="sr-card sr-story"><div className="sr-story-icon"><Truck size={21}/></div><div className="sr-eyebrow">TRANSPORTER DASHBOARD</div><h2>Drive, Deliver & Grow</h2><p>Find transparent delivery opportunities from verified StoneRate orders across your service area.</p></article>
          <article className="sr-card sr-story"><div className="sr-story-icon"><ReceiptText size={21}/></div><div className="sr-eyebrow">FULL TRANSPARENCY</div><h2>No Hidden Margins</h2><p>See complete trip details and transport rates before deciding which opportunity works for you.</p></article>
          <article className="sr-card sr-story"><div className="sr-story-icon"><Layers3 size={21}/></div><div className="sr-eyebrow">VERIFIED SOURCES</div><h2>Trusted Plant Network</h2><p>Review material and pickup information from verified stone sellers and sand yards.</p></article>
          <article className="sr-card sr-story"><div className="sr-story-icon"><PackageCheck size={21}/></div><div className="sr-eyebrow">DIRECT ORDERS</div><h2>Pick, Drop & Complete</h2><p>Accept buyer delivery opportunities, collect materials, deliver safely, and build your record.</p></article>
        </div>
        <div className="sr-story-dots" aria-hidden="true"><span className="sr-story-dot active"/><span className="sr-story-dot"/><span className="sr-story-dot"/><span className="sr-story-dot"/></div>
      </section>
      <section className="sr-section"><SectionHead eyebrow="LIVE PRICING" title="Today’s Market Rates" action="View all" onAction={onViewAllRates}/>{loading?<Skeletons count={3}/>:rates.length?<div className="sr-scroller sr-rates-grid">{rates.map(r=><MarketRateCard key={r.id} rate={r}/>)}</div>:<EmptyState icon={BadgeIndianRupee} title="No market rates available" text="Today’s verified material prices have not been published yet." action="Refresh rates" onAction={refresh}/>}</section>
      <section className="sr-section" aria-label="Quick business summary"><div className="sr-section-head sr-recent-orders-head"><div><h2>Recent Orders</h2></div></div>{loading?<Skeletons type="stat" count={4}/>:stats.length?<div className="sr-summary-grid">{stats.map(x=><article className={cx("sr-card sr-stat",x.tone)} key={x.label}><div className="sr-stat-top"><div className="sr-stat-icon"><img className="sr-stat-img" src={x.image} alt="" aria-hidden="true" loading="lazy" decoding="async" draggable="false"/></div></div><strong className="sr-stat-value">{x.value}</strong><span className="sr-stat-label">{x.label}</span></article>)}</div>:<EmptyState icon={Truck} title="No available trips" text="New delivery opportunities will appear here as they arrive." action="Browse Available Trips" onAction={onBrowseTrips}/>}</section>
      <section className="sr-section">{pickup?<article className="sr-card sr-pickup"><div className="sr-pickup-grid"><div><div className="sr-pickup-title"><Navigation size={17}/><span>NEXT PICKUP</span></div><h3>{pickup.pickupPlant}</h3><div className="sr-pickup-detail"><span><Layers3 size={12}/>{pickup.material} · {pickup.quantity}</span><span><Clock3 size={12}/>Pickup at {pickup.scheduledTime}</span><span><MapPin size={12}/>{pickup.distanceKm} km away</span></div></div><div className="sr-actions"><button className="sr-btn sr-btn-ghost" onClick={()=>call(pickup.phone)}><Phone size={14}/>Call</button><button className="sr-btn sr-btn-light" onClick={()=>navigate(pickup)}><Navigation size={14}/>Navigate</button></div></div></article>:<EmptyState icon={CalendarClock} title="You have no scheduled pickups" text="Accept an available trip to see your next pickup here." action="Browse Available Trips" onAction={onBrowseTrips}/>}</section>
      <section className="sr-section"><SectionHead title="Recent Orders" subtitle="Your latest delivery opportunities and active trips." action="View all" onAction={onViewAllOrders}/>{loading?<Skeletons count={3}/>:orders.length?<div className="sr-orders">{orders.map(o=><OrderCard key={o.id} order={o} onOpen={setSelected} onAccept={accept} onNavigate={navigate}/>)}</div>:<EmptyState icon={ClipboardList} title="No recent orders" text="Your latest delivery opportunities and active trips will appear here." action="Browse Available Trips" onAction={onBrowseTrips}/>}</section>
      <section className="sr-section">{snapshot?<article className="sr-card sr-order-snapshot"><div className="sr-earn-top"><div><div className="sr-eyebrow">FLEET ACTIVITY</div><h3>Order Snapshot</h3></div><ClipboardList size={21} color="#087f8c"/></div><div className="sr-snapshot-grid"><div className="sr-snapshot-metric"><small>TOTAL TRUCKS & QUANTITY</small><strong>{snapshot.totalTrucks} trucks</strong><span>{snapshot.totalQuantity} {snapshot.quantityUnit}</span></div><div className="sr-snapshot-metric"><small>TOTAL ORDERS</small><strong>{snapshot.totalOrders}</strong><span>All recorded orders</span></div><div className="sr-snapshot-metric"><small>THIS WEEK</small><strong>{snapshot.thisWeek}</strong><span>Orders this week</span></div><div className="sr-snapshot-metric"><small>THIS MONTH</small><strong>{snapshot.thisMonth}</strong><span>Orders this month</span></div></div><div className="sr-bars" aria-label="Seven-day order activity">{(snapshot.weekBars||[20,22,19,24,21,23,20]).map((v,i)=><span key={i} className="sr-bar" style={{height:`${Math.max(12,Math.min(100,v))}%`}} title={`Day ${i+1}: ${v}%`}/>)}</div><div className="sr-earn-foot"><span className="sr-progress-copy">Seven-day order activity</span><button className="sr-btn sr-btn-primary" onClick={onViewAllOrders}>View Orders<ChevronRight size={13}/></button></div></article>:<EmptyState icon={ClipboardList} title="No order history" text="Your fleet and order totals will appear after orders are created." action="Browse Available Trips" onAction={onBrowseTrips}/>}</section>
      </>}
    </main>
    <button className={cx("sr-refresh",refreshing&&"spinning")} aria-label="Refresh dashboard" onClick={refresh} disabled={refreshing}>{refreshing?<LoaderCircle size={18}/>:<RefreshCw size={18}/>}</button>
    <nav className="bd-bottom" aria-label="Mobile navigation">
      {NAV_ITEMS.map(item => { const Icon = item.icon; const active = item.label === "Home"; const badge = ({ Bidding: s?.availableTrips, Orders: unread })[item.label] || 0;
        return <button type="button" key={item.label} className={cx("bd-nav-item", active && "active")} aria-current={active ? "page" : undefined} onClick={() => navTo(item.label)}>
          {badge > 0 && <span className="bd-nav-badge">{Math.min(badge, 9)}</span>}
          {active ? <span className="bd-active-icon"><Icon size={NAV_ICON_ACTIVE}/></span> : <Icon size={NAV_ICON_SIZE}/>}
          <span>{item.label}</span>
        </button>; })}
    </nav>
    {drawer&&<><div className="sr-overlay" onClick={closeDrawer}/><aside className="sr-drawer" role="dialog" aria-modal="true" aria-label="Notifications"><div className="sr-drawer-head"><h2>Notifications</h2><IconButton label="Close notifications" onClick={closeDrawer}><X size={18}/></IconButton></div>{notes.length?notes.map(n=><button key={n.id} className={cx("sr-card sr-notification",!n.read&&"unread")} style={{width:"100%",textAlign:"left"}} onClick={()=>onNotificationRead(n)}><span className="sr-notification-icon">{n.type==="payment"?<IndianRupee size={16}/>:n.type==="trip"?<Truck size={16}/>:<Clock3 size={16}/>}</span><span><h3>{n.title}</h3><p>{n.message}</p><time>{n.createdAt}</time></span>{!n.read&&<i className="sr-unread-mark"/>}</button>):<EmptyState icon={Bell} title="You’re all caught up" text="New trip and payment alerts will appear here."/>}</aside></>}
    <Modal open={Boolean(selected)} title={selected?.deliveryId||"Order details"} onClose={closeModal}>{selected&&<><div className="sr-modal-route"><div className="sr-timeline"><div className="sr-stop"><span className="sr-stop-dot pickup"/><div><small>Pickup</small><strong>{selected.pickupName}</strong><small>{selected.pickupAddress}</small></div></div><div className="sr-stop"><span className="sr-stop-dot drop"/><div><small>Drop</small><strong>{selected.dropName}</strong><small>{selected.dropAddress}</small></div></div></div></div><div className="sr-modal-row"><span>Material</span><strong>{selected.materialName}</strong></div><div className="sr-modal-row"><span>Quantity</span><strong>{selected.quantity} {selected.quantityUnit}</strong></div><div className="sr-actions" style={{marginTop:14}}><button className="sr-btn sr-btn-primary" onClick={()=>navigate(selected)}><Navigation size={14}/>Navigate</button><button className="sr-btn" onClick={()=>call(selected.pickupPhone)}><Phone size={14}/>Call pickup</button></div></>}</Modal>
    {toast&&<div className="sr-toast" role="status">{toast}</div>}
  </div>;
}
